services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: server
    networks:
      shenet:
        ipv4_address: 172.10.10.77
    working_dir: /work
    volumes:
      - ./:/work
    tty: true
    stdin_open: true
    # 自動実行はしない
    command: [ "bash", "-lc", "sleep infinity" ]

  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    container_name: client
    privileged: true   # XDP attach のため。可能なら cap_add でもOK
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
    #   - SYS_RESOURCE
    # security_opt:
    #   - apparmor:unconfined
    networks:
      shenet:
        ipv4_address: 172.10.10.78
    working_dir: /work
    volumes:
      - ./:/work
      - /sys/fs/bpf:/sys/fs/bpf
    tty: true
    stdin_open: true
    command: [ "bash", "-lc", "sleep infinity" ]

networks:
  shenet:
    name: dragon_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.10.0/24
          gateway: 172.10.10.1
